### PR TITLE
Enumerated class with colours added - fix/5/text 

### LINKED ISSUE #5: Text colouring with arbitrary arguments
Please refator this method, so it only accepts colors from restricted supported range (i.e. use enum class for the argument type)
https://github.com/klarasindelarova/HangedMan/blob/f04638f00b2f6d7c15f93caced21131c393e53ca/src/Round.java#L90

Also it might be beneficial to move this method and related class fields to separate utility class.

### PR DESCRIPTION
**Pull request by klarasindelarova**
Colours for colouring already used letters can be picked by the programmer through enumerated class Colour.

### CODE REVIEW

File: src/ks/hangedman/Colour.java [hunk 1]
```diff
@@ -0,0 +1,23 @@
+package ks.hangedman;
+
+public enum Colour {
+
+    RED("\u001B[31m"),
+    GREEN ("\u001B[32m"),
```
Comment (sindema8) [inline src/ks/hangedman/Colour.java]: please reformat this to use whitespaces consistently throughout entire project. In this case, either remove spaces before parenthesis or add space for RED

File: src/ks/hangedman/Colour.java [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+    BLACK ("\u001B[30m"),
+    YELLOW ("\u001B[33m"),
+    BLUE ("\u001B[34m"),
+    PURPLE ("\u001B[35m"),
+    CYAN ("\u001B[36m"),
+    RESET ("\u001B[0m");
+
+    private String colourCode;
```
Comment (sindema8) [inline src/ks/hangedman/Colour.java]: this can and probably should be final

File: src/ks/hangedman/Colour.java [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+public enum Colour {
+
+    RED("\u001B[31m"),
+    GREEN ("\u001B[32m"),
+    BLACK ("\u001B[30m"),
+    YELLOW ("\u001B[33m"),
+    BLUE ("\u001B[34m"),
+    PURPLE ("\u001B[35m"),
+    CYAN ("\u001B[36m"),
+    RESET ("\u001B[0m");
```
Comment (sindema8) [inline src/ks/hangedman/Colour.java]: Should you allow to use RESET color to be passed as argument to the method? It seems confusing. I would use this ```"\u001B[0m"``` constant only directly in ```colourLetters(...)``` method and do not put in as enum value here.

**Review by sindema8 — APPROVED** [review]
👍
